---
swagger: "2.0"
info:
  description: "No description"
  version: "1.0.0"
  title: "test"
  termsOfService: ""
paths:
  /projects:
    get:
      summary: "List of projects"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Project"
    post:
      summary: "Add a project"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        201:
          description: "Status 201"
          schema:
            $ref: "#/definitions/Project"
  /projects/{id}:
    put:
      summary: "Modify a project"
      consumes:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /projects/{id}/customers:
    post:
      summary: "Add a customer to a project"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Customer"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /projects/{id}/customers/{id}:
    delete:
      summary: "Delete a member from project"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /projects/{id}/teams:
    get:
      summary: "List of teams of project"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Team"
    post:
      summary: "Add a team"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
  /projects/{id}/teams/{id}:
    put:
      summary: "Modify a team"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "id"
      in: "path"
      required: true
      type: "string"
definitions:
  Project:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        description: "name of the project"
      description:
        type: "string"
        description: "description of the project"
      customer:
        $ref: "#/definitions/Customer"
  Customer:
    type: "object"
    properties:
      id:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
  Team:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      project:
        $ref: "#/definitions/Project"
      members:
        type: "array"
        items:
          $ref: "#/definitions/Employee"
  Employee:
    type: "object"
    required:
    - "firstname"
    - "id"
    - "lastname"
    properties:
      id:
        type: "number"
      firstname:
        type: "string"
      lastname:
        type: "string"
      function:
        type: "string"
        description: "'Project manager', 'Project leader', 'Scrum master', 'Team leader',\
          \ 'Developer', 'Architect', 'Analyst'"
